"use client";

import React from "react";
import Image from "next/image";
import { TypeAnimation } from "react-type-animation";
import Link from "next/link";

const HeroSection = () => {
  return (
    <section>
      <div className="grid grid-cols-1 lg:grid-cols-12">
        <div className="col-span-7 place-self-center text-center sm:text-left">
          <h1 className=" text-4xl sm:text-5xl lg:text-7xl font-extrabold">
            <span className="text-transparent bg-clip-text bg-gradient-to-br from-cyan-600 via-cyan-800 to-cyan-900">
              Hi, I am{" "}
            </span>
            <br />
            <TypeAnimation
              sequence={["GiBot", 1000, "a Discord Bot", 1000]}
              wrapper="span"
              speed={1}
              repeat={Infinity}
            />
          </h1>
          <ul className="text-base sm:text-lg mb-6 lg:text-xl list-disc">
            <li>Discord Bot</li>
            <li>integrated with a lot of APIs</li>
            <li>Developed to improve my coding skills</li>
          </ul>
          <div>
            <Link
              href="https://www.linkedin.com/in/giovannibraga"
              target="_blank"
            >
              <button className="px-6 py-3 w-full sm:w-fit rounded-full mr-4 bg-gradient-to-br text-white from-cyan-950 via-cyan-800 to-cyan-600 hover:bg-slate-200 font-bold">
                LinkedIn
              </button>
            </Link>

            <Link
              href="https://github.com/giovannibraaga/gibott"
              target="_blank"
            >
              <button className="px-1 py-1 w-full sm:w-fit rounded-full bg-transparent bg-gradient-to-br from-cyan-950 via-cyan-800 to-cyan-600 mt-3 font-bold">
                <span className="block text-white rounded-full px-5 py-2">
                  Github
                </span>
              </button>
            </Link>
          </div>
        </div>
        <div className="col-span-5 place-self-center mt-4 lg:mt-0">
          <div className="rounded-full w-[250px] h-[250px] lg:w-[400px] lg:h-[400px] relative">
            <Link href="https://storyset.com/technology" target="_blank">
              <Image
                src={"/images/robot.svg"}
                alt="Robot image generated by storyset "
                className="absolute transform -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"
                height={600}
                width={600}
              />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
